name: "Run tests for Parser::FIT"
on:
  pull_request:
  push:
    branches:
      - main
  
jobs:
  test:
    runs-on: ubuntu-20.04
    name: "Run prove"
    steps:
      - uses: actions/checkout@v2
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.34'
          install-modules-with: cpanm
          install-modules-args: --with-develop
      - name: Run unit tests
        run: prove -vlr
      - name: Generate coverage report
        env: 
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
        run: |
          perl Makefile.PL
          cover -test -report coveralls +ignore '^local\/lib'
