name: "Run tests for Parser::FIT"
on: [pull_request, push]
  
jobs:
  test:
    runs-on: ubuntu-20.04
    name: "Run prove"
    steps:
      - uses: actions/checkout@v2
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.34'
      - run: cpanm --installdeps .
      - run: prove -lv t